repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
    -   id: black
        name: black
        description: black autoformatting
        entry: black
        args: ["--config=pyproject.toml"]
        language: python
        types: [python]
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: ["--config=.flake8"]
        language: python
        types: [python]
    -   id: mypy
        name: mypy
        entry: mypy
        args: ["--config-file", "mypy.ini"]
        language: python
        types: [python]
        pass_filenames: false
